version: "2"

services:
  repl:
    links:
      - testrpc
      - mongo
    depends_on:
      - truffle
    extends:
      file: ./docker-compose-base.yml
      service: dev-base
    volumes:
      - m2-repo:/root/.m2
    command: repl

  release:
    extends:
      file: ./docker-compose-base.yml
      service: build-base
    volumes:
      - m2-repo:/root/.m2
    command: release

  test-watch:
    links:
      - testrpc
      - mongo
    depends_on:
      - truffle
    extends:
      file: ./docker-compose-base.yml
      service: test-base
    volumes:
      - m2-repo:/root/.m2
    command: lein test-watch

  test:
    links:
      - testrpc
      - mongo
    depends_on:
      - truffle
    extends:
      file: ./docker-compose-base.yml
      service: test-base
    volumes:
      - m2-repo:/root/.m2
    command: lein test

  testrpc:
    image: beetleman/docker-eth-env:0.0.3

  truffle:
    build:
      context: .
      dockerfile: ./development/Dockerfile.truffle
    volumes:
      - ./development:/app
    environment:
      - RPC_HOST=testrpc
    links:
      - testrpc

  mongo:
    image: mongo:3.6.0

volumes:
  m2-repo:
