version: "2.2"

services:
  repl:
    links:
      - testrpc
      - mongo
    depends_on:
      - truffle
    extends:
      file: ./docker-compose-base.yml
      service: dev-base
    command: repl

  kibit:
    extends:
      file: ./docker-compose-base.yml
      service: test-base
    entrypoint: []
    command: lein kibit

  kibit-watch:
    extends:
      file: ./docker-compose-base.yml
      service: test-base
    entrypoint: []
    command: lein auto kibit


  test-watch:
    links:
      - testrpc
      - mongo
    depends_on:
      - truffle
    extends:
      file: ./docker-compose-base.yml
      service: test-base
    command: lein test-watch

  test:
    links:
      - testrpc
      - mongo
    depends_on:
      - truffle
    extends:
      file: ./docker-compose-base.yml
      service: test-base
    command: lein test

  testrpc:
    image: beetleman/docker-eth-env:0.0.10

  truffle:
    build:
      context: .
      dockerfile: ./development/Dockerfile.truffle
    volumes:
      - ./development:/app
    environment:
      - RPC_HOST=testrpc
    links:
      - testrpc

  mongo:
    image: mongo:3.6.0
