version: "2"

services:
  build-base:
    build:
      context: .
      dockerfile: ./development/Dockerfile.dev
    volumes:
      - .:/app

  dev-base:
    extends:
      service: build-base
    ports:
      - "7000:7000"
      - "3000:3000"
      - "9229:9229"
    environment:
      - RPC_URL=http://testrpc:8545
      - REDIS_URL=redis://redis:6379/0

  test-base:
    extends:
      service: build-base
    environment:
      - RPC_URL=http://testrpc:8545
      - REDIS_URL=redis://redis:6379/0
