version: "2.2"

services:
  repl:
    links:
      - testrpc
      - mongo
    depends_on:
      - truffle
    extends:
      file: ./docker-compose-base.yml
      service: dev-base
    volumes:
      - m2-repo:/root/.m2
    command: repl

  repl-kovan:
    links:
      - kovan:testrpc
      - mongo
    extends:
      file: ./docker-compose-base.yml
      service: dev-base
    volumes:
      - m2-repo:/root/.m2
    command: repl

  release:
    extends:
      file: ./docker-compose-base.yml
      service: build-base
    volumes:
      - m2-repo:/root/.m2
    command: release

  test-watch:
    links:
      - testrpc
      - mongo
    depends_on:
      - truffle
    extends:
      file: ./docker-compose-base.yml
      service: test-base
    volumes:
      - m2-repo:/root/.m2
    command: lein test-watch

  test:
    links:
      - testrpc
      - mongo
    depends_on:
      - truffle
    extends:
      file: ./docker-compose-base.yml
      service: test-base
    volumes:
      - m2-repo:/root/.m2
    command: lein test

  testrpc:
    image: beetleman/docker-eth-env:0.0.3

  kovan:
    image: parity/parity:v1.7.11
    container_name: parity-kovan
    cpus: 0.5
    volumes:
      - chain:/root/.local/share/io.parity.ethereum
    ports:
      - "8180:8180"
      - "30303:30303"
      - "8546:8546"
    command: --chain kovan --unsafe-expose --no-warp --tracing on ui

  truffle:
    build:
      context: .
      dockerfile: ./development/Dockerfile.truffle
    volumes:
      - ./development:/app
    environment:
      - RPC_HOST=testrpc
    links:
      - testrpc

  mongo:
    image: mongo:3.6.0

volumes:
  m2-repo:
  chain:
