version: "2"

services:
  app:
    extends:
      file: ./docker-compose-base.yml
      service: dev-base
    links:
      - testrpc
      - redis
    command: app

  repl:
    links:
      - testrpc
      - redis
    extends:
      file: ./docker-compose-base.yml
      service: dev-base
    command: repl

  testrpc:
    build:
      context: ./development/docker-eth-env
    volumes:
      - "/etc/localtime:/etc/localtime:ro"


  truffle:
    build:
      context: .
      dockerfile: ./development/Dockerfile.truffle
    volumes:
      - ./development:/app
    environment:
      - RPC_HOST=testrpc
    links:
      - testrpc

  redis:
    image: redis:4-alpine
