version: "2"

services:
  app:
    extends:
      file: ./docker-compose-base.yml
      service: dev-base
    links:
      - testrpc
      - redis
    command: app

  repl:
    links:
      - testrpc
      - redis
    extends:
      file: ./docker-compose-base.yml
      service: dev-base
    command: repl

  testrpc:
    build:
      context: ./development
      dockerfile: ./Dockerfile.testrpc

  redis:
    image: redis:4-alpine
