version: "2.2"

services:
  build-base:
    build:
      context: .
      dockerfile: ./development/Dockerfile.dev
    volumes:
      - ./:$PWD
    working_dir: $PWD
    entrypoint: ./development/run-dev.sh

  dev-base:
    extends:
      service: build-base
    ports:
      - "7000:7000"
      - "3000:3000"
      - "9229:9229"
    environment:
      - RPC_URL=http://testrpc:8545
      - MONGO_URL=mongodb://mongo:27017/dev
      - DB_NAME=scene

  test-base:
    extends:
      service: build-base
    environment:
      - RPC_URL=http://testrpc:8545
      - MONGO_URL=mongodb://mongo:27017/test
      - DB_NAME=scene_test
