version: "2.2"

services:
  app:
    container_name: app-kovan
    build:
      context: .
    links:
      - kovan
      - redis
      - couchdb
    ports:
      - "8000:8000"
    environment:
      - RPC_URL=http://kovan:8545
      - PORT=8000
      - CHUNK_SIZE=100000
      - COUCHDB_URL=http://admin:password@couchdb:5984
      - REDIS_URL=redis://redis:6379/0

  kovan:
    image: parity/parity:v1.8.3
    container_name: parity-kovan
    cpu_count: 1
    cpu_percent: 50
    volumes:
      - chain:/root/.local/share/io.parity.ethereum
    ports:
      - "8180:8180"
      - "30303:30303"
      - "8546:8546"
    command: --chain kovan --unsafe-expose --fat-db on ui

  couchdb:
    image: couchdb:2.1.1
    container_name: couchdb-kovan
    ports:
      - 5984:5984
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password

  redis:
    container_name: redis-kovan
    image: redis:4-alpine

volumes:
  chain:
