version: "2"

services:
  dev-base:
    build:
      context: .
      dockerfile: ./development/Dockerfile.dev
    volumes:
      - .:/app
    ports:
      - "7000:7000"
      - "3000:3000"
    environment:
      - RPC_URL=http://testrpc:8545
      - REDIS_URL=redis://redis:6379/0
